data:
  token_sequence_loader:
    hf_dataset_name: "HuggingFaceFW/fineweb"
    sequence_length: 256
  activations_harvester:
    llms:
      - name: google/gemma-2-2b
    harvesting_batch_size: 8
crosscoder:
  n_latents: 16384
  use_encoder_bias: True
  use_decoder_bias: True
  dec_init_norm: 0.01
cuda_device: 1
train:
  num_steps: 300000
  batch_size: 1024
  gradient_accumulation_steps_per_batch: 4
  save_every_n_steps: 10000
  log_every_n_steps: 10
  dead_latents_threshold_n_examples: 500000  # Number of zero-activating examples to consider a latent dead (used for logging only)

  final_lambda_s: 5  # L1-loss weight
  lambda_s_n_steps: 15000  # 5% of total steps (warmup period)

  # Buffer configuration
  buffer_size: 400  # Number of mini-batches in the buffer
  buffer_refill_ratio: 0.25  # When to trigger refilling (when 25% consumed)

  upload_saves_to_wandb: false
  optimizer:
    type: "adam"
    betas: [0.9, 0.999]
    learning_rate: 2e-4
    warmup_pct: 0.005
    warmdown_pct: 0.005
experiment_name: "l1_lambda_5"
seed: 10101
hookpoints: ["blocks.12.hook_resid_post","blocks.13.hook_resid_post","blocks.14.hook_resid_post","blocks.15.hook_resid_post","blocks.16.hook_resid_post","blocks.17.hook_resid_post","blocks.18.hook_resid_post","blocks.19.hook_resid_post","blocks.20.hook_resid_post","blocks.21.hook_resid_post"]
wandb:
  entity: jnainani-university-of-massachusetts-amherst
  project: acausal_cc_test2