data:
  token_sequence_loader:
    hf_dataset_name: "HuggingFaceFW/fineweb"
    sequence_length: 512
  activations_harvester:
    llms:
      # - name: EleutherAI/pythia-160M
      #   revision: step142000
      - name: google/gemma-2-2b
    harvesting_batch_size: 1
crosscoder:
  n_latents: 32768
  k: 150
  use_encoder_bias: True
  use_decoder_bias: True
cuda_device: 1 #doesnt work lmao
train:
  num_steps: 30000
  batch_size: 128
  save_every_n_steps: 3000
  log_every_n_steps: 10
  topk_style: "batch_topk"
  lambda_aux: 0.5
  upload_saves_to_wandb: false
experiment_name: "gemmarun3"
hookpoints: ["blocks.12.hook_resid_post","blocks.13.hook_resid_post","blocks.14.hook_resid_post","blocks.15.hook_resid_post","blocks.16.hook_resid_post", "blocks.17.hook_resid_post", "blocks.18.hook_resid_post", "blocks.19.hook_resid_post","blocks.20.hook_resid_post","blocks.21.hook_resid_post"]
wandb:
  entity: tim_hua
  project: acausal_cc_tests